// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// LunchMenusColumns holds the columns for the "lunch_menus" table.
	LunchMenusColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "resturant", Type: field.TypeString},
		{Name: "date", Type: field.TypeTime},
		{Name: "language", Type: field.TypeEnum, Nullable: true, Enums: []string{"se", "en"}},
		{Name: "menu", Type: field.TypeJSON},
	}
	// LunchMenusTable holds the schema information for the "lunch_menus" table.
	LunchMenusTable = &schema.Table{
		Name:       "lunch_menus",
		Columns:    LunchMenusColumns,
		PrimaryKey: []*schema.Column{LunchMenusColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "lunchmenu_resturant_date_language",
				Unique:  true,
				Columns: []*schema.Column{LunchMenusColumns[2], LunchMenusColumns[3], LunchMenusColumns[4]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		LunchMenusTable,
	}
)

func init() {
}
