// Code generated by ent, DO NOT EDIT.

package lunchmenu

const (
	// Label holds the string label denoting the lunchmenu type in the database.
	Label = "lunch_menu"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldDate holds the string denoting the date field in the database.
	FieldDate = "date"
	// EdgeItems holds the string denoting the items edge name in mutations.
	EdgeItems = "items"
	// EdgeResturant holds the string denoting the resturant edge name in mutations.
	EdgeResturant = "resturant"
	// Table holds the table name of the lunchmenu in the database.
	Table = "lunch_menus"
	// ItemsTable is the table that holds the items relation/edge.
	ItemsTable = "lunch_menu_items"
	// ItemsInverseTable is the table name for the LunchMenuItem entity.
	// It exists in this package in order to avoid circular dependency with the "lunchmenuitem" package.
	ItemsInverseTable = "lunch_menu_items"
	// ItemsColumn is the table column denoting the items relation/edge.
	ItemsColumn = "lunch_menu_items"
	// ResturantTable is the table that holds the resturant relation/edge.
	ResturantTable = "lunch_menus"
	// ResturantInverseTable is the table name for the Resturant entity.
	// It exists in this package in order to avoid circular dependency with the "resturant" package.
	ResturantInverseTable = "resturants"
	// ResturantColumn is the table column denoting the resturant relation/edge.
	ResturantColumn = "resturant_menu"
)

// Columns holds all SQL columns for lunchmenu fields.
var Columns = []string{
	FieldID,
	FieldDate,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "lunch_menus"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"resturant_menu",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}
