// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/dtekcth/dtek-api/ent/lunchmenu"
	"github.com/dtekcth/dtek-api/ent/predicate"
)

// LunchMenuDelete is the builder for deleting a LunchMenu entity.
type LunchMenuDelete struct {
	config
	hooks    []Hook
	mutation *LunchMenuMutation
}

// Where appends a list predicates to the LunchMenuDelete builder.
func (lmd *LunchMenuDelete) Where(ps ...predicate.LunchMenu) *LunchMenuDelete {
	lmd.mutation.Where(ps...)
	return lmd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (lmd *LunchMenuDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(lmd.hooks) == 0 {
		affected, err = lmd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*LunchMenuMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			lmd.mutation = mutation
			affected, err = lmd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(lmd.hooks) - 1; i >= 0; i-- {
			if lmd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = lmd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, lmd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (lmd *LunchMenuDelete) ExecX(ctx context.Context) int {
	n, err := lmd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (lmd *LunchMenuDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: lunchmenu.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: lunchmenu.FieldID,
			},
		},
	}
	if ps := lmd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, lmd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	return affected, err
}

// LunchMenuDeleteOne is the builder for deleting a single LunchMenu entity.
type LunchMenuDeleteOne struct {
	lmd *LunchMenuDelete
}

// Exec executes the deletion query.
func (lmdo *LunchMenuDeleteOne) Exec(ctx context.Context) error {
	n, err := lmdo.lmd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{lunchmenu.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (lmdo *LunchMenuDeleteOne) ExecX(ctx context.Context) {
	lmdo.lmd.ExecX(ctx)
}
