// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/dtekcth/dtek-api/ent/lunchmenuitem"
	"github.com/dtekcth/dtek-api/ent/predicate"
)

// LunchMenuItemDelete is the builder for deleting a LunchMenuItem entity.
type LunchMenuItemDelete struct {
	config
	hooks    []Hook
	mutation *LunchMenuItemMutation
}

// Where appends a list predicates to the LunchMenuItemDelete builder.
func (lmid *LunchMenuItemDelete) Where(ps ...predicate.LunchMenuItem) *LunchMenuItemDelete {
	lmid.mutation.Where(ps...)
	return lmid
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (lmid *LunchMenuItemDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(lmid.hooks) == 0 {
		affected, err = lmid.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*LunchMenuItemMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			lmid.mutation = mutation
			affected, err = lmid.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(lmid.hooks) - 1; i >= 0; i-- {
			if lmid.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = lmid.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, lmid.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (lmid *LunchMenuItemDelete) ExecX(ctx context.Context) int {
	n, err := lmid.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (lmid *LunchMenuItemDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: lunchmenuitem.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: lunchmenuitem.FieldID,
			},
		},
	}
	if ps := lmid.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, lmid.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	return affected, err
}

// LunchMenuItemDeleteOne is the builder for deleting a single LunchMenuItem entity.
type LunchMenuItemDeleteOne struct {
	lmid *LunchMenuItemDelete
}

// Exec executes the deletion query.
func (lmido *LunchMenuItemDeleteOne) Exec(ctx context.Context) error {
	n, err := lmido.lmid.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{lunchmenuitem.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (lmido *LunchMenuItemDeleteOne) ExecX(ctx context.Context) {
	lmido.lmid.ExecX(ctx)
}
