// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/dtekcth/dtek-api/ent/lunchmenu"
	"github.com/dtekcth/dtek-api/ent/resturant"
)

// ResturantCreate is the builder for creating a Resturant entity.
type ResturantCreate struct {
	config
	mutation *ResturantMutation
	hooks    []Hook
}

// SetSlug sets the "slug" field.
func (rc *ResturantCreate) SetSlug(s string) *ResturantCreate {
	rc.mutation.SetSlug(s)
	return rc
}

// SetName sets the "name" field.
func (rc *ResturantCreate) SetName(s string) *ResturantCreate {
	rc.mutation.SetName(s)
	return rc
}

// SetCampus sets the "campus" field.
func (rc *ResturantCreate) SetCampus(r resturant.Campus) *ResturantCreate {
	rc.mutation.SetCampus(r)
	return rc
}

// AddMenuIDs adds the "menu" edge to the LunchMenu entity by IDs.
func (rc *ResturantCreate) AddMenuIDs(ids ...int) *ResturantCreate {
	rc.mutation.AddMenuIDs(ids...)
	return rc
}

// AddMenu adds the "menu" edges to the LunchMenu entity.
func (rc *ResturantCreate) AddMenu(l ...*LunchMenu) *ResturantCreate {
	ids := make([]int, len(l))
	for i := range l {
		ids[i] = l[i].ID
	}
	return rc.AddMenuIDs(ids...)
}

// Mutation returns the ResturantMutation object of the builder.
func (rc *ResturantCreate) Mutation() *ResturantMutation {
	return rc.mutation
}

// Save creates the Resturant in the database.
func (rc *ResturantCreate) Save(ctx context.Context) (*Resturant, error) {
	var (
		err  error
		node *Resturant
	)
	if len(rc.hooks) == 0 {
		if err = rc.check(); err != nil {
			return nil, err
		}
		node, err = rc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ResturantMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = rc.check(); err != nil {
				return nil, err
			}
			rc.mutation = mutation
			if node, err = rc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(rc.hooks) - 1; i >= 0; i-- {
			if rc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = rc.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, rc.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*Resturant)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from ResturantMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (rc *ResturantCreate) SaveX(ctx context.Context) *Resturant {
	v, err := rc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (rc *ResturantCreate) Exec(ctx context.Context) error {
	_, err := rc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rc *ResturantCreate) ExecX(ctx context.Context) {
	if err := rc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (rc *ResturantCreate) check() error {
	if _, ok := rc.mutation.Slug(); !ok {
		return &ValidationError{Name: "slug", err: errors.New(`ent: missing required field "Resturant.slug"`)}
	}
	if _, ok := rc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Resturant.name"`)}
	}
	if _, ok := rc.mutation.Campus(); !ok {
		return &ValidationError{Name: "campus", err: errors.New(`ent: missing required field "Resturant.campus"`)}
	}
	if v, ok := rc.mutation.Campus(); ok {
		if err := resturant.CampusValidator(v); err != nil {
			return &ValidationError{Name: "campus", err: fmt.Errorf(`ent: validator failed for field "Resturant.campus": %w`, err)}
		}
	}
	return nil
}

func (rc *ResturantCreate) sqlSave(ctx context.Context) (*Resturant, error) {
	_node, _spec := rc.createSpec()
	if err := sqlgraph.CreateNode(ctx, rc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (rc *ResturantCreate) createSpec() (*Resturant, *sqlgraph.CreateSpec) {
	var (
		_node = &Resturant{config: rc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: resturant.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: resturant.FieldID,
			},
		}
	)
	if value, ok := rc.mutation.Slug(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: resturant.FieldSlug,
		})
		_node.Slug = value
	}
	if value, ok := rc.mutation.Name(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: resturant.FieldName,
		})
		_node.Name = value
	}
	if value, ok := rc.mutation.Campus(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeEnum,
			Value:  value,
			Column: resturant.FieldCampus,
		})
		_node.Campus = value
	}
	if nodes := rc.mutation.MenuIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   resturant.MenuTable,
			Columns: []string{resturant.MenuColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: lunchmenu.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ResturantCreateBulk is the builder for creating many Resturant entities in bulk.
type ResturantCreateBulk struct {
	config
	builders []*ResturantCreate
}

// Save creates the Resturant entities in the database.
func (rcb *ResturantCreateBulk) Save(ctx context.Context) ([]*Resturant, error) {
	specs := make([]*sqlgraph.CreateSpec, len(rcb.builders))
	nodes := make([]*Resturant, len(rcb.builders))
	mutators := make([]Mutator, len(rcb.builders))
	for i := range rcb.builders {
		func(i int, root context.Context) {
			builder := rcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ResturantMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, rcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, rcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, rcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (rcb *ResturantCreateBulk) SaveX(ctx context.Context) []*Resturant {
	v, err := rcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (rcb *ResturantCreateBulk) Exec(ctx context.Context) error {
	_, err := rcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rcb *ResturantCreateBulk) ExecX(ctx context.Context) {
	if err := rcb.Exec(ctx); err != nil {
		panic(err)
	}
}
