// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/dtekcth/dtek-api/ent/lunchmenu"
	"github.com/dtekcth/dtek-api/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	lunchmenuMixin := schema.LunchMenu{}.Mixin()
	lunchmenuMixinFields0 := lunchmenuMixin[0].Fields()
	_ = lunchmenuMixinFields0
	lunchmenuFields := schema.LunchMenu{}.Fields()
	_ = lunchmenuFields
	// lunchmenuDescUpdateTime is the schema descriptor for update_time field.
	lunchmenuDescUpdateTime := lunchmenuMixinFields0[0].Descriptor()
	// lunchmenu.DefaultUpdateTime holds the default value on creation for the update_time field.
	lunchmenu.DefaultUpdateTime = lunchmenuDescUpdateTime.Default.(func() time.Time)
	// lunchmenu.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	lunchmenu.UpdateDefaultUpdateTime = lunchmenuDescUpdateTime.UpdateDefault.(func() time.Time)
}
