// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/dtekcth/dtek-api/ent/lunchmenuitem"
	"github.com/dtekcth/dtek-api/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	lunchmenuitemFields := schema.LunchMenuItem{}.Fields()
	_ = lunchmenuitemFields
	// lunchmenuitemDescPreformatted is the schema descriptor for preformatted field.
	lunchmenuitemDescPreformatted := lunchmenuitemFields[3].Descriptor()
	// lunchmenuitem.DefaultPreformatted holds the default value on creation for the preformatted field.
	lunchmenuitem.DefaultPreformatted = lunchmenuitemDescPreformatted.Default.(bool)
}
