// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// LunchMenu is the predicate function for lunchmenu builders.
type LunchMenu func(*sql.Selector)

// LunchMenuItem is the predicate function for lunchmenuitem builders.
type LunchMenuItem func(*sql.Selector)

// Resturant is the predicate function for resturant builders.
type Resturant func(*sql.Selector)
